[package]
name = "keitaiso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vibrato = "0.5.1"
zstd = "0.12.4"
